### ISSUE TITLE
Make A Blade's files & Folders

### ISSUE THREAD

**Issue by dvlpaccount** [dvlpaccount/truthordare#1]
- commons
profile.blade.php
profile-edit.blade.php
donations.blade.php :'D
timeline.blade.php ( optional )

- truths
truth.blade.php
listf-guest.blade.php
views-truth.blade.php

- dares
dares.blade.php
listf-guest.blade.php
views-dare.blade.php

**Comment by NawfalHadi** [comment]
put the list page on the - commons folder
use the script for making a difference for truth list and dare's list with button
so if you click the truth button the list will change to truth lsit :D ok

**Comment by NawfalHadi** [comment]
so I just change this

- truths
truth.blade.php
listf-guest.blade.php

and this 

- dares
dares.blade.php
listf-guest.blade.php

truth and dare blade will put it on the same page that is list-page.blade.php with the script as a mark
and the listf-guest will put it on the listf-guest.blade but in the commons folder

**Comment by NawfalHadi** [comment]
I've done this issue I'll close this :D
