### ISSUE TITLE
Making a controller

### ISSUE THREAD

**Issue by dvlpaccount** [dvlpaccount/truthordare#2]
- UserController

**Create**
We will use this on the register.
**Read**
Here, we using a parameter for take the id and put on the profile page.
**Update**
On update form

- TruthController

**Create**
The guest or the another user will use this on the pop up of the truth's function that will pop up on the profile page.
**Read**
There's 2 read 
if the user that will pop up all truth question
else if another user that will pop up the same id from this another user's id
**Update**
The question can update if the user who asked not answer if the user already answer the question the user who ask a question can't change his question
**Delete**
Who ask the question can delete the question also the user but the questioner get notification if sipenanya delete that question

- DareController

Same like truth

- LikeTController

Just a user who asked can like

**Read**
List the post what the user like
**Update**
From the truth table update the like's row to 1 that's describe
**Edit**
Just unlike so update to the 0 again

- LikeDController

Same Like LikeTController but using a dare's table

- CommentTController

**Create**
The user and another user can comment The truth question
**Read**
When click the view all comment from id_truth will show up
**Update**
You can change your comment before
**Delete**
You can delete your controller

- CommentDController

Same like CommentTController

**Comment by NawfalHadi** [comment]
emh on that read UserController because Laravel has a default function for register and log in so we don't need to make the register function again

**Comment by NawfalHadi** [comment]
and on the 

- UserController
I see on another issue that we using another page for the update so I will use
the edit function and update so
the edit function will be used for moving to the edit page

**Comment by NawfalHadi** [comment]
- LikeTController
 for the read, we didn't need that so I remove it.

**Comment by NawfalHadi** [comment]
on like's function, we just need an update function for like and dislike from the answerer.
because from the default,  when you comment on the post that value of like will automatically to the 0 is meaning unlike and after you click it will be using update function and the value will change to the 1
