### ISSUE TITLE
Making a redirect to each other page

### ISSUE THREAD

**Issue by dvlpaccount** [dvlpaccount/truthordare#4]
This is the rute :

Login to profile
Edit Profile Button to EditPage
EditPage to profile

And when you click detail on the question you will move to the page that show you that question and the comment.

**Comment by NawfalHadi** [comment]
I wanna change the (login to profile)'s route to the Login -> Homepage -> profile
just put a pic of your's Profile Picture on the homepage.

**Comment by NawfalHadi** [comment]
home is the alpha version of timeline.

**Comment by NawfalHadi** [comment]
and I add more rute :
icon list -> list page
item on list -> itemView

**Comment by NawfalHadi** [comment]
I Just make it a redirect and then i do a migrate :D
